image: node:latest

stages:
  - build
cache:
  paths:
    - node_modules/

build-deploy-netlify-job:
  stage: build
  script:
    - cd "frontend"
    - npm install
    - npm run build
    - npm install -g netlify-cli
    - netlify deploy --prod --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID --dir build/
  only:
    changes:
      - "frontend"

